version: '3.8'

services:
  backend:
    network_mode: "host"
    build: .
    ports:
      - "8081:8081"
    environment:
      POSTGRES_USERNAME: battlecodes
      POSTGRES_PASSWORD: aV958MT/_Kcm
      POSTGRES_JDBC_URL: jdbc:postgresql://127.0.0.1:5432/battlecodes
