name: build and deploy spring-api
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: build and deploy spring-api
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup jdk 18
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 18

      - name: build the app
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: login to Docker Hub
        run: echo "dckr_pat_6WT_FrLGkS3D6gOM4sVReRzaPgw" | docker login -u "battlecodes" --password-stdin

      - name: build the docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: battlecodes/backend-battlecodes:latest

      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 1526
          script: |
            cd /home/backend/proj/
            docker pull battlecodes/backend-battlecodes:latest
            docker stop backend-container || true
            docker rm backend-container || true
            docker run --env-file /home/backend/proj/.env -d --name backend-container --network host battlecodes/backend-battlecodes:latest


