name: build and deploy spring-api
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: build and deploy spring-api
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup jdk 18
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 18

      - name: unit tests
        run: mvn -B test --file pom.xml

      - name: build the app
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: login to Docker Hub
        run: echo "${{ deploy.DOCKER_PASSWORD }}" | docker login -u "${{ deploy.DOCKER_USERNAME }}" --password-stdin

      - name: build the docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: battlecodes/backend-battlecodes:latest

      - name: SSH to server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ deploy.SERVER_HOST }}
          username: ${{ deploy.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker-compose down
            docker-compose pull
            docker-compose up -d
